CREATE USER boris_britva WITH PASSWORD '1234';

GRANT USAGE ON SCHEMA public TO boris_britva;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO boris_britva;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
   GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO boris_britva;