REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM boris_britva;

REVOKE USAGE ON SCHEMA public FROM boris_britva;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
   REVOKE ALL ON TABLES FROM boris_britva;

DROP USER IF EXISTS boris_britva;
