global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'wbl0'
    metrics_path: /metrics
    static_configs:
      - targets: ['wbl0:8081']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']